vim.opt.tabstop = 4
vim.opt.shiftwidth = 4
vim.opt.softtabstop = 4
vim.opt.expandtab = true
vim.opt.smarttab = true
vim.opt.autoindent = true
vim.opt.hlsearch = true
vim.opt.incsearch = true
vim.opt.ignorecase = true
vim.opt.smartcase = true
vim.opt.number = true
vim.opt.errorbells = false
vim.opt.hidden = true
vim.opt.backup = false
vim.opt.writebackup = false
vim.opt.swapfile = false
vim.opt.confirm = true
vim.opt.scrolloff = 8
vim.opt.termguicolors = true
vim.opt.background = "dark"
vim.opt.completeopt = { "menu", "menuone", "noselect" }
vim.opt.signcolumn = "yes"          -- always show gutter so gitsigns doesn't shift text
vim.opt.clipboard = "unnamedplus"   -- sync with system clipboard
vim.opt.splitright = true           -- vsplit opens right
vim.opt.splitbelow = true           -- split opens below
vim.opt.cursorline = true           -- highlight current line
vim.opt.wrap = false                -- no line wrap
vim.opt.updatetime = 250            -- faster gitsigns / hover response
