# Generated by matugen — do not edit manually.
# Re-generated by scripts/wallpaper-next.sh on each wallpaper rotation.
# Sourced by ~/.zshrc via: [[ -f ~/.config/fzf/colors.zsh ]] && source ~/.config/fzf/colors.zsh
export FZF_DEFAULT_OPTS=" \
  --color=bg+:{{ colors.surface_variant.dark.hex }},bg:{{ colors.background.dark.hex }},spinner:{{ colors.primary.dark.hex }},hl:{{ colors.error.dark.hex }} \
  --color=fg:{{ colors.on_background.dark.hex }},header:{{ colors.error.dark.hex }},info:{{ colors.primary.dark.hex }},pointer:{{ colors.primary.dark.hex }} \
  --color=marker:{{ colors.secondary.dark.hex }},fg+:{{ colors.on_surface.dark.hex }},prompt:{{ colors.primary.dark.hex }},hl+:{{ colors.error.dark.hex }} \
  --color=selected-bg:{{ colors.surface.dark.hex }} \
  --multi"
