" Generated by matugen — do not edit manually.
" Re-generated on each wallpaper change via scripts/wallpaper-apply.sh.
" Load with: colorscheme matugen  (or set via colorscheme-flavor.lua)

set background=dark
highlight clear
if exists("syntax_on")
  syntax reset
endif
let g:colors_name = "matugen"

" ── Core UI ───────────────────────────────────────────────────────────────────
hi Normal             guifg={{ colors.on_background.dark.hex }}   guibg={{ colors.background.dark.hex }}
hi NormalFloat        guifg={{ colors.on_surface.dark.hex }}       guibg={{ colors.surface.dark.hex }}
hi NormalNC           guifg={{ colors.on_surface_variant.dark.hex }} guibg={{ colors.background.dark.hex }}

hi Cursor             guifg={{ colors.background.dark.hex }}       guibg={{ colors.primary.dark.hex }}
hi CursorLine         guibg={{ colors.surface.dark.hex }}
hi CursorColumn       guibg={{ colors.surface.dark.hex }}
hi CursorLineNr       guifg={{ colors.primary.dark.hex }}          gui=bold

hi LineNr             guifg={{ colors.outline.dark.hex }}
hi SignColumn         guifg={{ colors.outline.dark.hex }}          guibg={{ colors.background.dark.hex }}
hi ColorColumn        guibg={{ colors.surface.dark.hex }}
hi FoldColumn         guifg={{ colors.outline.dark.hex }}          guibg={{ colors.background.dark.hex }}
hi Folded             guifg={{ colors.on_surface_variant.dark.hex }} guibg={{ colors.surface_variant.dark.hex }}

hi Visual             guibg={{ colors.primary_container.dark.hex }}
hi VisualNOS          guibg={{ colors.primary_container.dark.hex }}
hi Search             guifg={{ colors.on_primary_container.dark.hex }} guibg={{ colors.primary_container.dark.hex }}
hi IncSearch          guifg={{ colors.on_primary.dark.hex }}       guibg={{ colors.primary.dark.hex }} gui=bold
hi MatchParen         guifg={{ colors.primary.dark.hex }}          guibg={{ colors.surface_variant.dark.hex }} gui=bold

hi StatusLine         guifg={{ colors.on_surface.dark.hex }}       guibg={{ colors.surface_variant.dark.hex }}
hi StatusLineNC       guifg={{ colors.outline.dark.hex }}          guibg={{ colors.surface.dark.hex }}
hi WinSeparator       guifg={{ colors.outline_variant.dark.hex }}
hi TabLine            guifg={{ colors.on_surface_variant.dark.hex }} guibg={{ colors.surface_variant.dark.hex }}
hi TabLineSel         guifg={{ colors.on_primary_container.dark.hex }} guibg={{ colors.primary_container.dark.hex }} gui=bold
hi TabLineFill        guibg={{ colors.surface.dark.hex }}

hi Pmenu              guifg={{ colors.on_surface.dark.hex }}       guibg={{ colors.surface_variant.dark.hex }}
hi PmenuSel           guifg={{ colors.on_primary_container.dark.hex }} guibg={{ colors.primary_container.dark.hex }}
hi PmenuSbar          guibg={{ colors.surface_variant.dark.hex }}
hi PmenuThumb         guibg={{ colors.outline.dark.hex }}

hi FloatBorder        guifg={{ colors.outline.dark.hex }}          guibg={{ colors.surface.dark.hex }}
hi FloatTitle         guifg={{ colors.primary.dark.hex }}          guibg={{ colors.surface.dark.hex }} gui=bold

hi EndOfBuffer        guifg={{ colors.surface_variant.dark.hex }}
hi NonText            guifg={{ colors.outline_variant.dark.hex }}
hi SpecialKey         guifg={{ colors.outline.dark.hex }}
hi Whitespace         guifg={{ colors.surface_variant.dark.hex }}

hi SpellBad           guisp={{ colors.error.dark.hex }}            gui=undercurl
hi SpellCap           guisp={{ colors.secondary.dark.hex }}        gui=undercurl
hi SpellRare          guisp={{ colors.tertiary.dark.hex }}         gui=undercurl
hi SpellLocal         guisp={{ colors.primary.dark.hex }}          gui=undercurl

" ── Syntax ────────────────────────────────────────────────────────────────────
hi Comment            guifg={{ colors.outline.dark.hex }}          gui=italic
hi Constant           guifg={{ colors.tertiary.dark.hex }}
hi String             guifg={{ colors.on_tertiary_container.dark.hex }}
hi Character          guifg={{ colors.on_tertiary_container.dark.hex }}
hi Number             guifg={{ colors.on_primary_container.dark.hex }}
hi Boolean            guifg={{ colors.on_primary_container.dark.hex }}
hi Float              guifg={{ colors.on_primary_container.dark.hex }}
hi Identifier         guifg={{ colors.on_surface.dark.hex }}
hi Function           guifg={{ colors.tertiary.dark.hex }}          gui=bold
hi Statement          guifg={{ colors.primary.dark.hex }}
hi Conditional        guifg={{ colors.primary.dark.hex }}
hi Repeat             guifg={{ colors.primary.dark.hex }}
hi Label              guifg={{ colors.primary.dark.hex }}
hi Operator           guifg={{ colors.on_surface_variant.dark.hex }}
hi Keyword            guifg={{ colors.primary.dark.hex }}
hi Exception          guifg={{ colors.error.dark.hex }}
hi PreProc            guifg={{ colors.tertiary.dark.hex }}
hi Include            guifg={{ colors.tertiary.dark.hex }}
hi Define             guifg={{ colors.tertiary.dark.hex }}
hi Macro              guifg={{ colors.tertiary.dark.hex }}
hi Type               guifg={{ colors.secondary.dark.hex }}
hi StorageClass       guifg={{ colors.secondary.dark.hex }}
hi Structure          guifg={{ colors.secondary.dark.hex }}
hi Typedef            guifg={{ colors.secondary.dark.hex }}
hi Special            guifg={{ colors.secondary.dark.hex }}
hi SpecialChar        guifg={{ colors.on_tertiary_container.dark.hex }}
hi Tag                guifg={{ colors.primary.dark.hex }}
hi Delimiter          guifg={{ colors.on_surface_variant.dark.hex }}
hi SpecialComment     guifg={{ colors.on_surface_variant.dark.hex }} gui=italic
hi Error              guifg={{ colors.error.dark.hex }}
hi Todo               guifg={{ colors.on_primary.dark.hex }}       guibg={{ colors.primary.dark.hex }}
hi Underlined         gui=underline

" ── LSP Diagnostics ───────────────────────────────────────────────────────────
hi DiagnosticError              guifg={{ colors.error.dark.hex }}
hi DiagnosticWarn               guifg={{ colors.tertiary.dark.hex }}
hi DiagnosticInfo               guifg={{ colors.secondary.dark.hex }}
hi DiagnosticHint               guifg={{ colors.primary.dark.hex }}
hi DiagnosticUnnecessary        guifg={{ colors.outline.dark.hex }}
hi DiagnosticVirtualTextError   guifg={{ colors.error.dark.hex }}           gui=italic
hi DiagnosticVirtualTextWarn    guifg={{ colors.tertiary.dark.hex }}        gui=italic
hi DiagnosticVirtualTextInfo    guifg={{ colors.secondary.dark.hex }}       gui=italic
hi DiagnosticVirtualTextHint    guifg={{ colors.primary.dark.hex }}         gui=italic
hi DiagnosticUnderlineError     guisp={{ colors.error.dark.hex }}           gui=undercurl
hi DiagnosticUnderlineWarn      guisp={{ colors.tertiary.dark.hex }}        gui=undercurl
hi DiagnosticUnderlineInfo      guisp={{ colors.secondary.dark.hex }}       gui=undercurl
hi DiagnosticUnderlineHint      guisp={{ colors.primary.dark.hex }}         gui=undercurl

" ── Diff ──────────────────────────────────────────────────────────────────────
hi DiffAdd            guibg={{ colors.tertiary_container.dark.hex }}
hi DiffChange         guibg={{ colors.primary_container.dark.hex }}
hi DiffDelete         guifg={{ colors.error.dark.hex }}            guibg={{ colors.error_container.dark.hex }}
hi DiffText           guibg={{ colors.secondary_container.dark.hex }}
hi Added              guifg={{ colors.tertiary.dark.hex }}
hi Changed            guifg={{ colors.secondary.dark.hex }}
hi Removed            guifg={{ colors.error.dark.hex }}

" ── Treesitter ────────────────────────────────────────────────────────────────
hi @variable                    guifg={{ colors.on_surface.dark.hex }}
hi @variable.builtin            guifg={{ colors.tertiary.dark.hex }}
hi @variable.parameter          guifg={{ colors.on_surface_variant.dark.hex }}
hi @constant.builtin            guifg={{ colors.on_primary_container.dark.hex }} gui=bold
hi @string.escape               guifg={{ colors.on_tertiary_container.dark.hex }} gui=bold
hi @function.builtin            guifg={{ colors.tertiary.dark.hex }}        gui=bold
hi @constructor                 guifg={{ colors.secondary.dark.hex }}
hi @attribute                   guifg={{ colors.tertiary.dark.hex }}
hi @module                      guifg={{ colors.on_surface.dark.hex }}
hi @punctuation.bracket         guifg={{ colors.on_surface_variant.dark.hex }}
hi @punctuation.delimiter       guifg={{ colors.on_surface_variant.dark.hex }}
hi @tag                         guifg={{ colors.primary.dark.hex }}
hi @tag.attribute               guifg={{ colors.secondary.dark.hex }}
hi @tag.delimiter               guifg={{ colors.on_surface_variant.dark.hex }}
hi @markup.heading              guifg={{ colors.primary.dark.hex }}         gui=bold
hi @markup.link                 guifg={{ colors.tertiary.dark.hex }}        gui=underline
hi @markup.raw                  guifg={{ colors.on_tertiary_container.dark.hex }}

" ── Telescope ─────────────────────────────────────────────────────────────────
hi TelescopeNormal              guifg={{ colors.on_surface.dark.hex }}      guibg={{ colors.surface.dark.hex }}
hi TelescopeBorder              guifg={{ colors.outline.dark.hex }}         guibg={{ colors.surface.dark.hex }}
hi TelescopeSelection           guibg={{ colors.primary_container.dark.hex }}
hi TelescopeMatching            guifg={{ colors.primary.dark.hex }}         gui=bold
hi TelescopePromptPrefix        guifg={{ colors.primary.dark.hex }}

" ── NvimTree ──────────────────────────────────────────────────────────────────
hi NvimTreeNormal               guifg={{ colors.on_surface.dark.hex }}      guibg={{ colors.surface.dark.hex }}
hi NvimTreeFolderIcon           guifg={{ colors.primary.dark.hex }}
hi NvimTreeRootFolder           guifg={{ colors.primary.dark.hex }}         gui=bold
hi NvimTreeExecFile             guifg={{ colors.tertiary.dark.hex }}
hi NvimTreeSpecialFile          guifg={{ colors.secondary.dark.hex }}
hi NvimTreeSymlink              guifg={{ colors.tertiary.dark.hex }}
hi NvimTreeGitDirty             guifg={{ colors.tertiary.dark.hex }}
hi NvimTreeGitNew               guifg={{ colors.tertiary.dark.hex }}

" ── nvim-cmp ──────────────────────────────────────────────────────────────────
hi CmpItemAbbr                  guifg={{ colors.on_surface.dark.hex }}
hi CmpItemAbbrMatch             guifg={{ colors.primary.dark.hex }}         gui=bold
hi CmpItemAbbrMatchFuzzy        guifg={{ colors.primary.dark.hex }}
hi CmpItemKind                  guifg={{ colors.secondary.dark.hex }}
hi CmpItemMenu                  guifg={{ colors.outline.dark.hex }}

" ── GitSigns ──────────────────────────────────────────────────────────────────
hi GitSignsAdd                  guifg={{ colors.tertiary.dark.hex }}
hi GitSignsChange               guifg={{ colors.secondary.dark.hex }}
hi GitSignsDelete               guifg={{ colors.error.dark.hex }}
