[General]
backgroundFill={{ colors.background.dark.hex }}
basicTextColor={{ colors.on_background.dark.hex }}
passwordCursorColor={{ colors.primary.dark.hex }}
passwordInputBackground={{ colors.surface_variant.dark.hex }}
passwordTextColor={{ colors.on_background.dark.hex }}
wrongPasswordBorderColor={{ colors.error.dark.hex }}
passwordInputBorderColor={{ colors.primary.dark.hex }}
font=JetBrains Mono Nerd Font
blurRadius=32
passwordInputRadius=8
passwordInputBorderWidth=3
wrongPasswordBorderRadius=4
showUsersByDefault=true
showUserRealNameByDefault=false
passwordFontSize=32
usersFontSize=18
