# Generated by linux-setup theme switcher — do not edit manually.
# Re-generate: scripts/theme-switch.sh
export FZF_DEFAULT_OPTS=" \
  --color=bg+:${SURFACE0},bg:${BASE},spinner:${ROSEWATER},hl:${RED} \
  --color=fg:${TEXT},header:${RED},info:${ACCENT},pointer:${ROSEWATER} \
  --color=marker:${LAVENDER},fg+:${TEXT},prompt:${ACCENT},hl+:${RED} \
  --color=selected-bg:${SURFACE1} \
  --multi"
