# Generated by linux-setup theme switcher.

foreground              ${TEXT}
background              ${BASE}
selection_foreground    ${BASE}
selection_background    ${ACCENT}

color0  ${SURFACE1}
color8  ${SURFACE2}

color1  ${RED}
color9  ${RED}

color2  ${GREEN}
color10 ${GREEN}

color3  ${YELLOW}
color11 ${YELLOW}

color4  ${BLUE}
color12 ${BLUE}

color5  ${ACCENT}
color13 ${ACCENT}

color6  ${SKY}
color14 ${SKY}

color7  ${SUBTEXT1}
color15 ${SUBTEXT0}

cursor            ${ROSEWATER}
cursor_text_color ${BASE}

url_color         ${BLUE}

active_tab_foreground   ${BASE}
active_tab_background   ${ACCENT}
inactive_tab_foreground ${TEXT}
inactive_tab_background ${MANTLE}
