/**
 * ${THEME}/${FLAVOR} color scheme for Rofi
 * Generated by linux-setup theme switcher — do not edit manually
 * Re-generate: scripts/theme-switch.sh
 **/

* {
    rosewater:             ${ROSEWATER};
    flamingo:              ${FLAMINGO};
    pink:                  ${PINK};
    mauve:                 ${MAUVE};
    red:                   ${RED};
    maroon:                ${MAROON};
    peach:                 ${PEACH};
    yellow:                ${YELLOW};
    green:                 ${GREEN};
    teal:                  ${TEAL};
    sky:                   ${SKY};
    sapphire:              ${SAPPHIRE};
    blue:                  ${BLUE};
    lavender:              ${LAVENDER};
    text:                  ${TEXT};
    subtext1:              ${SUBTEXT1};
    subtext0:              ${SUBTEXT0};
    overlay2:              ${OVERLAY2};
    overlay1:              ${OVERLAY1};
    overlay0:              ${OVERLAY0};
    surface2:              ${SURFACE2};
    surface1:              ${SURFACE1};
    surface0:              ${SURFACE0};
    base:                  ${BASE};
    mantle:                ${MANTLE};
    crust:                 ${CRUST};
    accent:                ${ACCENT};
    background:            ${BASE};
    background-alt:        ${MANTLE};
    foreground:            ${TEXT};
    selected:              ${ACCENT};
    active:                ${GREEN};
    urgent:                ${RED};
}
