# ~/.config/starship.toml
# Generated by linux-setup theme switcher — do not edit manually.
# Re-generate: scripts/theme-switch.sh
#
# Segments: os  directory  git  languages  docker  cmd_duration    time (right)
# No backgrounds, no powerline. Colored symbols + text only.

"$schema" = 'https://starship.rs/config-schema.json'

palette = '${STARSHIP_PALETTE_NAME}'

format = """
$os$directory$git_branch$git_status\
$c$rust$golang$nodejs$php$java$kotlin$haskell$python\
$docker_context$cmd_duration
$character"""

right_format = '$time'

# --- OS icon ---
[os]
disabled = false
format   = '[$symbol](fg:red)'

[os.symbols]
Linux   = "󰌽 "
Debian  = "󰣚 "
Ubuntu  = "󰕈 "
Windows = " "
Macos   = "󰀵 "
Arch    = "󰣇 "
Fedora  = "󰣛 "
Manjaro = " "

# --- Username (SSH / root only) ---
[username]
show_always = false
style_user  = "fg:subtext0"
style_root  = "fg:red bold"
format      = '[$user ](style)'

# --- Directory ---
[directory]
style             = "fg:peach bold"
format            = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music"     = "󰝚 "
"Pictures"  = " "

# --- Git ---
[git_branch]
symbol = " "
format = '[$symbol$branch ](fg:yellow)'

[git_status]
format     = '([$all_status$ahead_behind ](fg:yellow))'
up_to_date = ''
modified   = '~${count}'
staged     = '+${count}'
untracked  = '?${count}'
deleted    = '✘${count}'
renamed    = '»${count}'
stashed    = '≡'
ahead      = '⇡${count}'
behind     = '⇣${count}'
diverged   = '⇕⇡${ahead_count}⇣${behind_count}'
conflicted = '⚡${count}'

# --- Languages (only shown when in a matching project) ---
[c]
symbol = " "
format = '[$symbol$version ](fg:green)'

[rust]
symbol = " "
format = '[$symbol$version ](fg:green)'

[golang]
symbol = " "
format = '[$symbol$version ](fg:green)'

[nodejs]
symbol = " "
format = '[$symbol$version ](fg:green)'

[php]
symbol = " "
format = '[$symbol$version ](fg:green)'

[java]
symbol = " "
format = '[$symbol$version ](fg:green)'

[kotlin]
symbol = " "
format = '[$symbol$version ](fg:green)'

[haskell]
symbol = " "
format = '[$symbol$version ](fg:green)'

[python]
symbol = " "
format = '[$symbol$version ](fg:green)'

# --- Docker ---
[docker_context]
symbol = " "
format = '[$symbol$context ](fg:sapphire)'

# --- Command duration (inline, subtle) ---
[cmd_duration]
disabled          = false
min_time          = 2000
show_milliseconds = false
format            = '[took $duration ](fg:overlay1)'

# --- Time (right-aligned) ---
[time]
disabled    = false
time_format = "%R"
format      = '[  $time](fg:lavender)'

# --- Prompt character ---
[character]
disabled                  = false
success_symbol            = '[❯](bold fg:green)'
error_symbol              = '[❯](bold fg:red)'
vimcmd_symbol             = '[❮](bold fg:green)'
vimcmd_replace_one_symbol = '[❮](bold fg:lavender)'
vimcmd_replace_symbol     = '[❮](bold fg:lavender)'
vimcmd_visual_symbol      = '[❮](bold fg:yellow)'

# --- ${STARSHIP_PALETTE_NAME} palette ---
[palettes.${STARSHIP_PALETTE_NAME}]
rosewater = '${ROSEWATER}'
flamingo  = '${FLAMINGO}'
pink      = '${PINK}'
mauve     = '${MAUVE}'
red       = '${RED}'
maroon    = '${MAROON}'
peach     = '${PEACH}'
yellow    = '${YELLOW}'
green     = '${GREEN}'
teal      = '${TEAL}'
sky       = '${SKY}'
sapphire  = '${SAPPHIRE}'
blue      = '${BLUE}'
lavender  = '${LAVENDER}'
text      = '${TEXT}'
subtext1  = '${SUBTEXT1}'
subtext0  = '${SUBTEXT0}'
overlay2  = '${OVERLAY2}'
overlay1  = '${OVERLAY1}'
overlay0  = '${OVERLAY0}'
surface2  = '${SURFACE2}'
surface1  = '${SURFACE1}'
surface0  = '${SURFACE0}'
base      = '${BASE}'
mantle    = '${MANTLE}'
crust     = '${CRUST}'
