#!/usr/bin/env bash

# shellcheck disable=SC1091
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/theme-common.sh"

theme_apply_editors_adapter() {
  local nvim_flavor_file="$HOME/.config/nvim/lua/colorscheme-flavor.lua"
  local flavor
  flavor="$(theme_context_get "derived.nvim_flavor")"

  if [[ "${THEME_DRY_RUN}" == "1" ]]; then
    echo "[dry-run] write ${nvim_flavor_file} with flavor=${flavor}"
    return 0
  fi

  mkdir -p "$(dirname "$nvim_flavor_file")"
  printf '-- Generated by linux-setup theme switcher. Do not edit manually.\nreturn "%s"\n' \
    "$flavor" > "$nvim_flavor_file"
  theme_info "Editors adapter completed (nvim flavor: ${flavor})"
}
