#!/usr/bin/env bash

# shellcheck disable=SC1091
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/theme-common.sh"

theme_apply_editors_adapter() {
  local nvim_flavor_file="$HOME/.config/nvim/lua/colorscheme-flavor.lua"
  local plugin flavor
  plugin="$(theme_context_get "derived.nvim_plugin")"
  flavor="$(theme_context_get "derived.nvim_flavor")"

  if [[ "${THEME_DRY_RUN}" == "1" ]]; then
    echo "[dry-run] write ${nvim_flavor_file} with plugin=${plugin} flavor=${flavor}"
    return 0
  fi

  mkdir -p "$(dirname "$nvim_flavor_file")"
  printf '-- Generated by linux-setup theme switcher. Do not edit manually.\nreturn { plugin = "%s", flavor = "%s" }\n' \
    "$plugin" "$flavor" > "$nvim_flavor_file"

  # Clear lazy.nvim's luacache so the new colorscheme is picked up on next nvim start
  local nvim_cache="${XDG_CACHE_HOME:-$HOME/.cache}/nvim/luac"
  if [[ -d "$nvim_cache" ]]; then
    find "$nvim_cache" -name "*colorscheme*" -delete 2>/dev/null || true
  fi

  theme_info "Editors adapter completed (nvim: ${plugin}/${flavor})"
}
